services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: appdb
    volumes:
      - ./db:/var/lib/postgresql/data
  apiteddy:
    build:
      context: .
    env_file:
      - ./.env
    container_name: encurtaLinks
    command: ["npm", "run", "start:api"]
    ports:
      - "3333:3333"
    restart: unless-stopped
    depends_on:
      - postgres

volumes: {}